# Generated by Django 5.2.4 on 2025-07-30 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('responsibilities', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(blank=True, max_length=100)),
                ('client_number', models.IntegerField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_sub', models.CharField(blank=True, max_length=255)),
                ('education_institution', models.CharField(blank=True, max_length=255)),
                ('education_degree', models.CharField(blank=True, max_length=255)),
                ('education_year', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=255)),
                ('service_description', models.TextField(blank=True)),
                ('service_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('testimonial_text', models.TextField(blank=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('about_me', models.TextField(blank=True)),
                ('about_me_intro', models.CharField(blank=True, max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('degree', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('about_me_description', models.TextField(blank=True)),
                ('skill_que', models.CharField(blank=True, max_length=255)),
                ('skill_ans', models.CharField(blank=True, max_length=255)),
                ('skill_progress', models.IntegerField(blank=True, default=0)),
                ('portfolio_text', models.TextField(blank=True)),
                ('services_text', models.TextField(blank=True)),
                ('testimonial_text', models.TextField(blank=True)),
                ('professional_experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='voicetest.professionalexperience')),
                ('project_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='voicetest.project_number')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='voicetest.resume')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='voicetest.services')),
                ('testimonial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='voicetest.testimonial')),
            ],
        ),
    ]
